// forge/grow/init.ts — Phase 0: seed the world-grown/ substrate.
//
// Creates world-grown/ and populates it from the current forge seed:
//   graph.json     ← forge/seeds/zone_graph.yaml (all zones get growth_step: 0)
//   blueprint.json ← empty stub
//   grammar/       ← copied from world/grammar/ (the living library)
//   zones/
//   entities/
//   quests/
//   <shared assets> ← symlinked from world/ so the engine can boot WORLD_DIR=world-grown/
//
// Usage:
//   npm run forge:init-world
//
// Idempotent: re-running does not overwrite graph.json or blueprint.json
// (use --force to reset), but always refreshes symlinks.

import { mkdirSync, existsSync, symlinkSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadSeed } from '../lib/seeds.ts';
import {
  grownWorldDir, isInitialized,
  saveGraph, saveBlueprint,
  stageZoneDef, stageArtifact, connectionsFor,
  type GrownGraph, type GrownBlueprint,
} from './worldState.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');
const WORLD_SRC = join(REPO_ROOT, 'world');

// Shared assets: symlinked so the engine resolves world/ refs without copying.
const SHARED_SYMLINKS = [
  'abilities',
  'tilesets',
  'biome-params.json',
  'entities/items/materials.yaml',
  'entities/items/archetypes.yaml',
  'entities/items/affixes',
];

// Accumulated content directories (empty to start; grow steps fill them in).
const CONTENT_DIRS = [
  'zones',
  'entities/mobs',
  'entities/items/bases',
  'quests',
  'prefabs',
];

function ensureSymlink(target: string, link: string): void {
  if (existsSync(link)) return;   // already linked (or real file)
  mkdirSync(dirname(link), { recursive: true });
  symlinkSync(target, link);
}

async function main(): Promise<void> {
  const force = process.argv.includes('--force');
  const worldDir = grownWorldDir();
  const seed = loadSeed();

  console.log(`world-grown dir: ${worldDir}`);
  mkdirSync(worldDir, { recursive: true });

  // ── Shared symlinks ──────────────────────────────────────────────────────────
  for (const rel of SHARED_SYMLINKS) {
    ensureSymlink(join(WORLD_SRC, rel), join(worldDir, rel));
  }
  console.log('  symlinks: ok');

  // ── Empty content directories ────────────────────────────────────────────────
  for (const rel of CONTENT_DIRS) {
    mkdirSync(join(worldDir, rel), { recursive: true });
  }

  // Grammar is NOT copied here: world/grammar/ is the single canonical library
  // the grower and the inventor both read/write. The engine never reads grammar
  // (it's a pipeline concern), so a per-world copy would only diverge.

  // ── graph.json ───────────────────────────────────────────────────────────────
  const graphPath = join(worldDir, 'graph.json');
  if (!existsSync(graphPath) || force) {
    const graph: GrownGraph = {
      generation: 0,
      seeded_at: new Date().toISOString(),
      zones: seed.graph.zones.map((z) => ({ ...z, growth_step: 0 })),
    };
    saveGraph(worldDir, graph);
    console.log(`  graph.json: seeded with ${graph.zones.length} zones`);
  } else {
    console.log('  graph.json: already exists (use --force to overwrite)');
  }

  // ── blueprint.json ───────────────────────────────────────────────────────────
  const blueprintPath = join(worldDir, 'blueprint.json');
  if (!existsSync(blueprintPath) || force) {
    const blueprint: GrownBlueprint = {
      initialized_at: new Date().toISOString(),
      storyline: '',
      lore_history: [],
      regions: [],
    };
    saveBlueprint(worldDir, blueprint);
    console.log('  blueprint.json: initialized (empty)');
  } else {
    console.log('  blueprint.json: already exists (use --force to overwrite)');
  }

  // ── world.yaml stub (loader needs this to boot WORLD_DIR=world-grown/) ───────
  const worldYamlPath = join(worldDir, 'world.yaml');
  if (!existsSync(worldYamlPath)) {
    writeFileSync(worldYamlPath, '# world-grown — generated by forge:init-world\n');
  }

  // ── Stage bare zone JSON files from the seed graph ───────────────────────────
  // The server loads zones from zones/*.json — without these the world is empty.
  // Zones are bare (no spawns/enhancements) until `forge:grow` steps add content.
  const startVillage = seed.graph.zones
    .filter((z) => z.biome === 'village')
    .sort((a, b) => a.level_band.tier - b.level_band.tier)[0];

  for (const z of seed.graph.zones) {
    const connections = connectionsFor(z.id, z.links);
    const spawns: Array<{ entity: string; count: number; respawn_seconds: number }> = [];

    // Seed the start village with a greeter NPC so the world is walkable on day 0.
    if (startVillage && z.id === startVillage.id) {
      const greeterId = `npc_${z.id}_elder`;
      spawns.push({ entity: greeterId, count: 1, respawn_seconds: 86400 });
      stageArtifact(worldDir, `entities/mobs/${greeterId}.yaml`, {
        id: greeterId,
        name: 'Village Elder',
        sprite: 'merchant_01',
        level: 1,
        role: 'npc',
        speed: 0,
        behavior: 'idle',
        aggro_range: 0,
        dialogue: ['Welcome, traveler. The road ahead is not safe. Rest here first.'],
      });
    }

    stageZoneDef(worldDir, {
      id: z.id,
      biome: z.biome,
      seed: z.seed,
      level_band: z.level_band,
      ...(Object.keys(connections).length ? { connections } : {}),
      ...(z.features.length ? { features: z.features } : {}),
      ...(spawns.length ? { spawns } : {}),
    });
  }
  console.log(`  zones: ${seed.graph.zones.length} staged from seed graph`);

  console.log('\nDone. Boot with:  WORLD_DIR=world-grown/ npm start');
  console.log('Grow:            npm run forge:grow');
}

main().catch((err) => { console.error(err); process.exit(1); });
