// Flat ESLint config. Deliberately thin: this repo's real correctness gate is
// `npm run typecheck` (four tsc projects), so lint is here for the classes of
// mistake the compiler doesn't catch — unused bindings, accidental globals,
// unreachable branches — and not for style. Formatting rules are intentionally
// absent; there is no prettier here and the surrounding code's style is the
// convention.
import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // Generated, vendored, or not-ours. `archive/` is kept-for-reference code,
    // `sprites/env` is a python venv, `world/` and `data/` are content.
    ignores: [
      'archive/**',
      // forge/out is generated by the forge runs; it is output, not source.
      'forge/out/**',
      'client/dist/**',
      'client/public/**',
      'data/**',
      'logs/**',
      'sprites/env/**',
      'world/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.ts', '**/*.js'],
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      // `catch {}` is the idiom here for a best-effort read that is allowed to
      // fail (a missing optional file, a stale watcher handle).
      'no-empty': ['error', { allowEmptyCatch: true }],
      // Only flag a destructuring pattern when EVERY binding in it could be
      // const — splitting `let { value, raw } = f()` apart to satisfy one half
      // makes the call site worse, not better.
      'prefer-const': ['error', { destructuring: 'all' }],
      // An `any` is usually a shortcut around a shape from YAML/JSON the loader
      // hasn't narrowed yet. Worth seeing, not worth failing the build over.
      '@typescript-eslint/no-explicit-any': 'warn',
      // A leading underscore is the opt-out for a binding kept for its position
      // (destructuring, an interface-shaped callback arg).
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // The one CommonJS file (pm2 reads it with require()).
    files: ['**/*.cjs'],
    languageOptions: { sourceType: 'commonjs', globals: globals.node },
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
  {
    // Tools and pipeline scripts are CLIs: console output is their interface.
    files: ['tools/**/*.ts', 'pipeline/**/*.ts', 'forge/**/*.ts', 'scripts/**/*.ts'],
    rules: { 'no-console': 'off' },
  },
);
