// Bundles forge/out/mob-candidates/*.yaml into a single data.js the static
// review page can <script src> directly — avoids fetch()/CORS so the page
// works opened straight from disk (file://), no server needed.
//   npx tsx tools/mob-candidates-build.ts
//   npx tsx tools/mob-candidates-build.ts --dir forge/out/mob-candidates
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import yaml from 'js-yaml';

function arg(name: string, def: string): string {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] && !process.argv[i + 1]!.startsWith('--') ? process.argv[i + 1]! : def;
}
const dir = arg('dir', join('forge', 'out', 'mob-candidates'));

const files = readdirSync(dir).filter((f) => f.endsWith('.yaml')).sort();
const candidates = files.map((f) => {
  const doc = yaml.load(readFileSync(join(dir, f), 'utf8')) as { mob: Record<string, unknown>; minted_abilities: unknown[] };
  return { file: f, mob: doc.mob, minted_abilities: doc.minted_abilities ?? [] };
});

const out = `// AUTO-GENERATED by tools/mob-candidates-build.ts — do not edit by hand.\nwindow.MOB_CANDIDATES = ${JSON.stringify(candidates, null, 2)};\n`;
writeFileSync(join(dir, 'data.js'), out, 'utf8');
console.log(`wrote ${candidates.length} candidate(s) to ${join(dir, 'data.js')}`);
